import type {
  InteractiveTutorialChapter,
  InteractiveTutorialStep,
} from "@/app/interactiveTutorial/interactiveTutorialTypes";

const operationsSteps = [
  {
    id: "roster-tab",
    title: "Open Config",
    instruction: "Open Config from the sidebar.",
    selector: '[data-tutorial-target="sidebar-tab-config"]',
  },
  {
    id: "directory-view",
    title: "Open Directory",
    instruction: "Choose Directory to manage demo people.",
    selector: '[data-tutorial-target="config-view-config-directory"]',
  },
  {
    id: "create-student",
    title: "Add a student",
    instruction: "In Students, click + and save a new student.",
    selector: '[data-tutorial-target="create-student-button"]',
  },
  {
    id: "inventory-tab",
    title: "Open Inventory",
    instruction: "Open Inventory from the sidebar.",
    selector: '[data-tutorial-target="sidebar-tab-inventory"]',
  },
  {
    id: "inventory-materials",
    title: "Open Materials",
    instruction: "Switch Inventory to the Materials subtab.",
    selector: '[data-tutorial-target="inventory-view-inventory-materials"]',
  },
  {
    id: "create-material",
    title: "Add material",
    instruction: "Use Add and save one material.",
    selector: '[data-tutorial-target="create-material-button"]',
  },
  {
    id: "material-filter",
    title: "Filter materials",
    instruction: "Apply at least one material filter.",
    selector: '.materials-toolbar',
  },
  {
    id: "material-edit",
    title: "Edit a material",
    instruction: "Click any material row to open edit mode.",
    selector: '[data-tutorial-target="edit-material-row"]',
  },
  {
    id: "inventory-parts",
    title: "Open Parts",
    instruction: "Switch Inventory to the Parts subtab.",
    selector: '[data-tutorial-target="inventory-view-inventory-parts"]',
  },
  {
    id: "create-part",
    title: "Add part definition",
    instruction: "Use Add and save one part definition.",
    selector: '[data-tutorial-target="create-part-button"]',
  },
  {
    id: "part-search",
    title: "Search parts",
    instruction: "Type in the parts search box.",
    selector: '[data-tutorial-target="parts-search-input"]',
  },
  {
    id: "inventory-purchases",
    title: "Open Purchases",
    instruction: "Switch Inventory to the Purchases subtab.",
    selector: '[data-tutorial-target="inventory-view-inventory-purchases"]',
  },
  {
    id: "create-purchase",
    title: "Add purchase request",
    instruction: "Use Add and save one purchase request.",
    selector: '[data-tutorial-target="create-purchase-button"]',
  },
  {
    id: "purchase-sort",
    title: "Sort or filter purchases",
    instruction: "Use the Purchases status control.",
    selector: '.purchase-toolbar',
  },
  {
    id: "workflow-tab",
    title: "Open Subsystems",
    instruction: "Open Readiness from the sidebar.",
    selector: '[data-tutorial-target="sidebar-tab-readiness"]',
  },
  {
    id: "subsystems-view",
    title: "Open Subsystems",
    instruction: "Choose Subsystems in Readiness.",
    selector: '[data-tutorial-target="readiness-view-readiness-subsystems"]',
  },
  {
    id: "create-subsystem",
    title: "Create a subsystem",
    instruction: "Use Add subsystem and save it.",
    selector: '[data-tutorial-target="create-subsystem-button"]',
  },
  {
    id: "edit-subsystem",
    title: "Edit a subsystem",
    instruction: "Click the subsystem edit icon.",
    selector: '[data-tutorial-target="edit-subsystem-button"]',
  },
  {
    id: "create-mechanism",
    title: "Add a mechanism",
    instruction: "Use Add mechanism and save it.",
    selector: '[data-tutorial-target="create-mechanism-button"]',
  },
  {
    id: "edit-mechanism",
    title: "Edit a mechanism",
    instruction: "Click a mechanism edit icon.",
    selector: '[data-tutorial-target="edit-mechanism-button"]',
  },
  {
    id: "add-part-to-mechanism",
    title: "Add a part to a mechanism",
    instruction: "Use the Add part button on a mechanism and save it.",
    selector: '[data-tutorial-target="add-part-to-mechanism-button"]',
  },
  {
    id: "manufacturing-tab",
    title: "Open Manufacturing",
    instruction: "Open Tasks from the sidebar.",
    selector: '[data-tutorial-target="sidebar-tab-tasks"]',
  },
  {
    id: "manufacturing-cnc",
    title: "Open manufacturing queue",
    instruction: "Choose Manufacturing in Tasks.",
    selector: '[data-tutorial-target="tasks-view-tasks-manufacturing"]',
  },
  {
    id: "create-cnc-job",
    title: "Add CNC job",
    instruction: "Use Add, choose CNC as the process, and save the job.",
    selector: '[data-tutorial-target="manufacturing-create-job-button"]',
  },
  {
    id: "inspect-cnc-job",
    title: "Inspect a CNC job",
    instruction: "Click any CNC row to open the job editor.",
    selector: '[data-tutorial-target="manufacturing-edit-job-row"]',
  },
  {
    id: "create-print-job",
    title: "Add 3D print job",
    instruction: "Use Add, choose 3D print as the process, and save the job.",
    selector: '[data-tutorial-target="manufacturing-create-job-button"]',
  },
  {
    id: "complete-print-job",
    title: "Complete a 3D print job",
    instruction: "Open a print job and save it with Complete status.",
    selector: '[data-tutorial-target="manufacturing-edit-job-row"]',
  },
  {
    id: "manufacturing-search",
    title: "Search manufacturing queue",
    instruction: "Use the manufacturing queue search box.",
    selector: '[data-tutorial-target="manufacturing-search-input"]',
  },
  {
    id: "create-fabrication-job",
    title: "Add fabrication job",
    instruction: "Use Add, choose Fabrication as the process, and save the job.",
    selector: '[data-tutorial-target="manufacturing-create-job-button"]',
  },
  {
    id: "inspect-fabrication-job",
    title: "Inspect a fabrication job",
    instruction: "Click any fabrication row to open the job editor.",
    selector: '[data-tutorial-target="manufacturing-edit-job-row"]',
  },
] satisfies InteractiveTutorialStep[];

export const operationsChapter = {
  id: "operations",
  title: "Chapter 2: Build Operations",
  summary: "Roster, Inventory, Subsystems, and Manufacturing end-to-end.",
  preferredProjectType: "robot",
  steps: operationsSteps,
} satisfies InteractiveTutorialChapter;
