import { EMPTY_BOOTSTRAP } from "@/features/workspace/shared/model/bootstrapDefaults";
import type { BootstrapPayload } from "@/types/bootstrap";

const memberOne = {
  id: "member-1",
  name: "Alex Builder",
  email: "alex@example.com",
  role: "student" as const,
  elevated: false,
  seasonId: "season-1",
};

const memberTwo = {
  ...memberOne,
  id: "member-2",
  name: "Blair Fabricator",
  email: "blair@example.com",
};

const baseTask: BootstrapPayload["tasks"][number] = {
  id: "task-1",
  projectId: "project-1",
  workstreamIds: [],
  subsystemIds: ["subsystem-1"],
  workTypeId: "",
  responsibleGroupId: null,
  mechanismIds: [],
  partInstanceIds: [],
  title: "Member one task",
  summary: "",
  scheduleRefs: [],
  requestedById: null,
  photoUrl: "",
  ownerId: "member-1",
  assigneeIds: [],
  mentorId: null,
  startDate: "2026-04-20",
  dueDate: "2026-04-22",
  priority: "medium",
  status: "not-started",

  checklistItems: [],
  manufacturingDetails: null,
  estimatedHours: 1,
  actualHours: 0,
  requiresDocumentation: false,
};

export function createBootstrap(): BootstrapPayload {
  return {
    ...EMPTY_BOOTSTRAP,
    members: [memberOne, memberTwo],
    projects: [
      {
        id: "project-1",
        seasonId: "season-1",
        name: "Robot",
        projectType: "robot",
        description: "",
        status: "active",
      },
    ],
    subsystems: [
      {
        id: "subsystem-1",
        projectId: "project-1",
        name: "Drive",
        color: "#123456",
        description: "",
        photoUrl: "",
        iteration: 1,
        isCore: true,
        parentSubsystemId: null,
        responsibleEngineerId: null,
        mentorIds: [],
      },
    ],
    tasks: [
      baseTask,
      {
        ...baseTask,
        id: "task-2",
        title: "Member two task",
        ownerId: "member-2",
      },
    ],
    reports: [
      {
        id: "report-1",
        reportType: "qa",
        projectId: "project-1",
        targetRefs: [{ kind: "task", id: "task-1" }],
        participantIds: ["member-1"],
        mentorId: null,
        requestedById: null,
        summary: "",
        result: "pass",
        createdByMemberId: "member-1",
        notes: "",
        reviewedAt: "2026-04-20",
        createdAt: "2026-04-20T00:00:00.000Z",
        status: "reviewed",
      },
      {
        id: "report-2",
        reportType: "qa",
        projectId: "project-1",
        targetRefs: [{ kind: "task", id: "task-2" }],
        participantIds: ["member-2"],
        mentorId: null,
        requestedById: null,
        summary: "",
        result: "pass",
        createdByMemberId: "member-2",
        notes: "",
        reviewedAt: "2026-04-21",
        createdAt: "2026-04-21T00:00:00.000Z",
        status: "reviewed",
      },
    ],
    risks: [
      {
        id: "risk-1",
        projectId: "project-1",
        title: "Member one risk",
        detail: "Only Alex should see this",
        severity: "high",
        category: "qa",
        status: "open",
        blocksWork: true,
        source: { kind: "report", id: "report-1" },
        relatedTargets: [{ kind: "task", id: "task-1" }],
        mitigationTaskId: "task-1",
        ownerGroupId: null,
        createdAt: "2026-04-20",
        updatedAt: "2026-04-20",
        resolvedAt: null,
      },
      {
        id: "risk-2",
        projectId: "project-1",
        title: "Member two risk",
        detail: "Blair owns this",
        severity: "high",
        category: "qa",
        status: "open",
        blocksWork: true,
        source: { kind: "report", id: "report-2" },
        relatedTargets: [{ kind: "task", id: "task-2" }],
        mitigationTaskId: "task-2",
        ownerGroupId: null,
        createdAt: "2026-04-20",
        updatedAt: "2026-04-20",
        resolvedAt: null,
      },
    ],
  };
}

export function createMetricsBootstrap(): BootstrapPayload {
  const base = createBootstrap();
  const metricsTasks: BootstrapPayload["tasks"] = Array.from({ length: 26 }, (_, index) => ({
    ...baseTask,
    id: `metric-task-${index + 1}`,
    title: `Metric task ${index + 1}`,
    status: index === 0 ? "complete" : index === 1 ? "waiting-for-qa" : "not-started",
    estimatedHours: index < 24 ? 5 : 15,
    ownerId: index % 8 === 0 ? null : "member-1",
    assigneeIds: index % 8 === 0 ? [] : ["member-1"],
  }));

  return {
    ...base,
    mechanisms: [
      {
        id: "mechanism-1",
        subsystemId: "subsystem-1",
        name: "Drive module",
        description: "",
        googleSheetsUrl: "",
        photoUrl: "",
        iteration: 1,
      },
    ],
    reports: [
      ...base.reports,
      {
        id: "report-qa-waiting",
        reportType: "qa",
        projectId: "project-1",
        targetRefs: [{ kind: "task", id: "metric-task-2" }],
        participantIds: ["member-1"],
        mentorId: null,
        requestedById: null,
        summary: "",
        result: "minor-fix",
        createdByMemberId: "member-1",
        notes: "",
        reviewedAt: "2026-04-30",
        createdAt: "2026-04-30T00:00:00.000Z",
        status: "submitted",
      },
    ],
    risks: [
      {
        id: "risk-blocker-1", projectId: "project-1", title: "Design issue", detail: "design issue", category: "design",
        severity: "high",
        status: "open",
        blocksWork: true,
        source: { kind: "manual" },
        relatedTargets: [{ kind: "task", id: "metric-task-3" }],
        mitigationTaskId: null,
        ownerGroupId: null,
        createdAt: "2026-04-25T00:00:00.000Z",
        updatedAt: "2026-04-25T00:00:00.000Z",
        resolvedAt: null,
      },
      {
        id: "risk-blocker-2", projectId: "project-1", title: "Lost part", detail: "lost part", category: "inventory",
        severity: "medium",
        status: "open",
        blocksWork: true,
        source: { kind: "manual" },
        relatedTargets: [{ kind: "task", id: "metric-task-4" }],
        mitigationTaskId: null,
        ownerGroupId: null,
        createdAt: "2026-04-26T00:00:00.000Z",
        updatedAt: "2026-04-26T00:00:00.000Z",
        resolvedAt: null,
      },
    ],
    tasks: metricsTasks,
    workLogs: [
      {
        id: "worklog-1",
        taskId: "metric-task-1",
        date: "2026-05-01",
        hours: 39.3,
        participantIds: ["member-1"],
        notes: "Initial implementation",
      },
    ],
  };
}
