import type { MechanismEditorModal } from "../modals/structure/MechanismEditorModal";
import type { SubsystemEditorModal } from "../modals/structure/SubsystemEditorModal";
import type { PartInstanceEditorModal } from "../modals/assetCatalog/PartInstanceEditorModal";
import type { PartDefinitionEditorModal } from "../modals/assetCatalog/PartDefinitionEditorModal";
import type { WorkstreamEditorModal } from "../modals/assetCatalog/WorkstreamEditorModal";
import type { ArtifactEditorModal } from "../modals/assetCatalog/ArtifactEditorModal";
import type { ComponentProps, Dispatch, FormEvent, SetStateAction } from "react";

import type { ManufacturingModalMode, MilestoneReportModalMode, PurchaseModalMode, QaReportModalMode, TaskModalMode, WorkLogModalMode } from "@/features/workspace/shared/model/workspaceModalModes";
import type { ManufacturingItemPayload, PurchaseItemPayload, QaReportPayload, TaskPayload, TestResultPayload, WorkLogPayload } from "@/types/payloads";
import type { BootstrapPayload } from "@/types/bootstrap";
import type { TaskRecord } from "@/types/recordsExecution";

import type { MaterialEditorModal } from "../modals/assetCatalog/MaterialEditorModal";

export interface WorkspaceModalHostViewProps {
  mechanismEditor: Omit<ComponentProps<typeof MechanismEditorModal>, "bootstrap" | "requestPhotoUpload" | "mechanismModalMode"> & { mechanismModalMode: "create" | "edit" | null };
  subsystemEditor: Omit<ComponentProps<typeof SubsystemEditorModal>, "bootstrap" | "requestPhotoUpload" | "subsystemModalMode"> & { subsystemModalMode: "create" | "edit" | null };
  partInstanceEditor: Omit<ComponentProps<typeof PartInstanceEditorModal>, "bootstrap" | "requestPhotoUpload" | "partDefinitionDraftsById" | "partInstanceModalMode"> & { partInstanceModalMode: "create" | "edit" | null };
  partDefinitionEditor: Omit<ComponentProps<typeof PartDefinitionEditorModal>, "bootstrap" | "requestPhotoUpload" | "partDefinitionModalMode"> & { partDefinitionModalMode: "create" | "edit" | null };
  workstreamEditor: Omit<ComponentProps<typeof WorkstreamEditorModal>, "bootstrap" | "workstreamModalMode"> & { workstreamModalMode: "create" | "edit" | null };
  artifactEditor: Omit<ComponentProps<typeof ArtifactEditorModal>, "bootstrap" | "artifactModalMode"> & { artifactModalMode: "create" | "edit" | null };
  materialEditor: ComponentProps<typeof MaterialEditorModal>;
  activeTask: TaskRecord | null;
  activeTimelineTaskDetail: TaskRecord | null;
  bootstrap: BootstrapPayload;
  mechanismsById: Record<string, BootstrapPayload["mechanisms"][number]>;
  partDefinitionsById: Record<string, BootstrapPayload["partDefinitions"][number]>;
  partInstancesById: Record<string, BootstrapPayload["partInstances"][number]>;
  closeManufacturingModal: () => void;
  closePurchaseModal: () => void;
  closeQaReportModal: () => void;
  closeMilestoneReportModal: () => void;
  closeTimelineTaskDetailsModal: () => void;
  closeWorkLogModal: () => void;
  openCreateWorkLogModal: (taskId?: string) => void;
  openCreateQaReportModal: (taskId?: string) => void;
  closeTaskModal: () => void;
  onTaskEditCanceled: () => void;
  requestPhotoUpload: (projectId: string, file: File) => Promise<string>;
  disciplinesById: Record<string, BootstrapPayload["disciplines"][number]>;
  milestonesById: Record<string, BootstrapPayload["milestones"][number]>;
  handleDeleteTask: (taskId: string) => Promise<void>;
  handleResolveTaskBlocker: (blockerId: string) => Promise<void>;
  handleManufacturingSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handlePurchaseSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleQaReportSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleMilestoneReportSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleWorkLogSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleTaskSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  onOpenTaskEditFromTimelineDetails: (task: TaskRecord) => void;
  openTaskDetailsModal: (task: TaskRecord) => void;
  isDeletingTask: boolean;
  isSavingManufacturing: boolean;
  isSavingPurchase: boolean;
  isSavingQaReport: boolean;
  isSavingMilestoneReport: boolean;
  isSavingWorkLog: boolean;
  isSavingTask: boolean;
  manufacturingDraft: ManufacturingItemPayload;
  manufacturingModalMode: ManufacturingModalMode;
  mentors: BootstrapPayload["members"];
  purchaseDraft: PurchaseItemPayload;
  purchaseFinalCost: string;
  purchaseModalMode: PurchaseModalMode;
  qaReportDraft: QaReportPayload;
  qaReportModalMode: QaReportModalMode;
  milestoneReportDraft: TestResultPayload;
  milestoneReportFindings: string;
  milestoneReportModalMode: MilestoneReportModalMode;
  workLogDraft: WorkLogPayload;
  workLogModalMode: WorkLogModalMode;
  setManufacturingDraft: Dispatch<SetStateAction<ManufacturingItemPayload>>;
  setPurchaseDraft: Dispatch<SetStateAction<PurchaseItemPayload>>;
  setPurchaseFinalCost: (value: string) => void;
  setQaReportDraft: Dispatch<SetStateAction<QaReportPayload>>;
  setMilestoneReportDraft: Dispatch<SetStateAction<TestResultPayload>>;
  setMilestoneReportFindings: (value: string) => void;
  setWorkLogDraft: Dispatch<SetStateAction<WorkLogPayload>>;
  setTaskDraft: Dispatch<SetStateAction<TaskPayload>>;
  showTimelineCreateToggleInTaskModal: boolean;
  onSwitchTaskCreateToMilestone: () => void;
  students: BootstrapPayload["members"];
  taskDraft: TaskPayload;
  taskModalMode: TaskModalMode;
}
