import type { Dispatch, FormEvent, SetStateAction } from "react";

import type { ArtifactModalMode, ManufacturingModalMode, MaterialModalMode, MechanismModalMode, MilestoneReportModalMode, PartDefinitionModalMode, PartInstanceModalMode, PurchaseModalMode, QaReportModalMode, SubsystemModalMode, TaskModalMode, WorkLogModalMode, WorkstreamModalMode } from "@/features/workspace/shared/model/workspaceModalModes";
import type { ArtifactPayload, ManufacturingItemPayload, MaterialPayload, MechanismPayload, PartDefinitionPayload, PartInstancePayload, PurchaseItemPayload, QaReportPayload, SubsystemPayload, TaskPayload, TestResultPayload, WorkLogPayload, WorkstreamPayload } from "@/types/payloads";
import type { BootstrapPayload } from "@/types/bootstrap";
import type { TaskRecord } from "@/types/recordsExecution";

export interface WorkspaceModalHostViewProps {
  activeArtifactId: string | null;
  activePartDefinitionId: string | null;
  activeMaterialId: string | null;
  activeMechanismId: string | null;
  activeWorkstreamId: string | null;
  activeSubsystemId: string | null;
  activeTask: TaskRecord | null;
  activeTimelineTaskDetail: TaskRecord | null;
  bootstrap: BootstrapPayload;
  closeManufacturingModal: () => void;
  closeArtifactModal: () => void;
  closeMaterialModal: () => void;
  closeMechanismModal: () => void;
  closePartInstanceModal: () => void;
  closePartDefinitionModal: () => void;
  closePurchaseModal: () => void;
  closeQaReportModal: () => void;
  closeMilestoneReportModal: () => void;
  closeTimelineTaskDetailsModal: () => void;
  closeWorkLogModal: () => void;
  closeSubsystemModal: () => void;
  closeTaskModal: () => void;
  closeWorkstreamModal: () => void;
  onTaskEditCanceled: () => void;
  requestPhotoUpload: (projectId: string, file: File) => Promise<string>;
  disciplinesById: Record<string, BootstrapPayload["disciplines"][number]>;
  milestonesById: Record<string, BootstrapPayload["milestones"][number]>;
  handleDeleteMaterial: (materialId: string) => Promise<void>;
  handleDeleteArtifact: (artifactId: string) => Promise<void>;
  handleToggleArtifactArchived: (artifactId: string) => Promise<void>;
  handleDeletePartDefinition: (partDefinitionId: string) => Promise<void>;
  handleDeleteMechanism: (mechanismId: string) => Promise<void>;
  handleTogglePartDefinitionArchived: (partDefinitionId: string) => Promise<void>;
  handleToggleSubsystemArchived: (subsystemId: string) => Promise<void>;
  handleToggleMechanismArchived: (mechanismId: string) => Promise<void>;
  handleToggleWorkstreamArchived: (workstreamId: string) => Promise<void>;
  handleDeleteTask: (taskId: string) => Promise<void>;
  handleResolveTaskBlocker: (blockerId: string) => Promise<void>;
  handlePartInstanceSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleManufacturingSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleMaterialSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleMechanismSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handlePartDefinitionSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleArtifactSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handlePurchaseSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleQaReportSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleMilestoneReportSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleWorkLogSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleSubsystemSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleTaskSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  handleWorkstreamSubmit: (milestone: FormEvent<HTMLFormElement>) => Promise<void>;
  onOpenTaskEditFromTimelineDetails: (task: TaskRecord) => void;
  openTaskDetailsModal: (task: TaskRecord) => void;
  isDeletingMaterial: boolean;
  isDeletingArtifact: boolean;
  isDeletingPartDefinition: boolean;
  isDeletingMechanism: boolean;
  isDeletingTask: boolean;
  isSavingManufacturing: boolean;
  isSavingArtifact: boolean;
  isSavingMaterial: boolean;
  isSavingPartDefinition: boolean;
  isSavingPartInstance: boolean;
  isSavingMechanism: boolean;
  isSavingPurchase: boolean;
  isSavingQaReport: boolean;
  isSavingMilestoneReport: boolean;
  isSavingWorkLog: boolean;
  isSavingSubsystem: boolean;
  isSavingTask: boolean;
  isSavingWorkstream: boolean;
  artifactDraft: ArtifactPayload;
  artifactModalMode: ArtifactModalMode;
  manufacturingDraft: ManufacturingItemPayload;
  manufacturingModalMode: ManufacturingModalMode;
  materialDraft: MaterialPayload;
  materialModalMode: MaterialModalMode;
  mechanismDraft: MechanismPayload;
  mechanismModalMode: MechanismModalMode;
  mechanismsById: Record<string, BootstrapPayload["mechanisms"][number]>;
  mentors: BootstrapPayload["members"];
  partInstanceDraft: PartInstancePayload;
  partInstanceModalMode: PartInstanceModalMode;
  partDefinitionDraft: PartDefinitionPayload;
  partDefinitionModalMode: PartDefinitionModalMode;
  partDefinitionsById: Record<string, BootstrapPayload["partDefinitions"][number]>;
  partInstancesById: Record<string, BootstrapPayload["partInstances"][number]>;
  purchaseDraft: PurchaseItemPayload;
  purchaseFinalCost: string;
  purchaseModalMode: PurchaseModalMode;
  qaReportDraft: QaReportPayload;
  qaReportModalMode: QaReportModalMode;
  milestoneReportDraft: TestResultPayload;
  milestoneReportFindings: string;
  milestoneReportModalMode: MilestoneReportModalMode;
  workLogDraft: WorkLogPayload;
  workLogModalMode: WorkLogModalMode;
  workstreamDraft: WorkstreamPayload;
  workstreamModalMode: WorkstreamModalMode;
  setArtifactDraft: Dispatch<SetStateAction<ArtifactPayload>>;
  setManufacturingDraft: Dispatch<SetStateAction<ManufacturingItemPayload>>;
  setMaterialDraft: Dispatch<SetStateAction<MaterialPayload>>;
  setMechanismDraft: Dispatch<SetStateAction<MechanismPayload>>;
  setPartInstanceDraft: Dispatch<SetStateAction<PartInstancePayload>>;
  setPartDefinitionDraft: Dispatch<SetStateAction<PartDefinitionPayload>>;
  setPurchaseDraft: Dispatch<SetStateAction<PurchaseItemPayload>>;
  setPurchaseFinalCost: (value: string) => void;
  setQaReportDraft: Dispatch<SetStateAction<QaReportPayload>>;
  setMilestoneReportDraft: Dispatch<SetStateAction<TestResultPayload>>;
  setMilestoneReportFindings: (value: string) => void;
  setWorkLogDraft: Dispatch<SetStateAction<WorkLogPayload>>;
  setWorkstreamDraft: Dispatch<SetStateAction<WorkstreamPayload>>;
  setSubsystemDraft: Dispatch<SetStateAction<SubsystemPayload>>;
  setSubsystemDraftRisks: (value: string) => void;
  setTaskDraft: Dispatch<SetStateAction<TaskPayload>>;
  showTimelineCreateToggleInTaskModal: boolean;
  onSwitchTaskCreateToMilestone: () => void;
  students: BootstrapPayload["members"];
  subsystemDraft: SubsystemPayload;
  subsystemDraftRisks: string;
  subsystemModalMode: SubsystemModalMode;
  taskDraft: TaskPayload;
  taskModalMode: TaskModalMode;
}
