import type { AppWorkspaceCatalogActions } from "@/app/hooks/useAppWorkspaceCatalogActions";
import type { AppWorkspaceModel } from "@/app/hooks/useAppWorkspaceModel";
import type { AppWorkspaceReportActions } from "@/app/hooks/useAppWorkspaceReportActions";
import type { AppWorkspaceRosterActions } from "@/app/hooks/useAppWorkspaceRosterActions";
import type { AppWorkspaceTaskActions } from "@/app/hooks/useAppWorkspaceTaskActions";

export const shellModalLayerModelKeys = [
  "activeArtifactId",
  "activeMaterialId",
  "activeMechanismId",
  "activePartDefinitionId",
  "activeSubsystemId",
  "activeTask",
  "activeTimelineTaskDetail",
  "activeWorkstreamId",
  "artifactDraft",
  "artifactModalMode",
  "disciplinesById",
  "interactiveTutorialOverlayProps",
  "isDeletingArtifact",
  "isDeletingMaterial",
  "isDeletingMechanism",
  "isDeletingPartDefinition",
  "isDeletingTask",
  "isSavingArtifact",
  "isSavingManufacturing",
  "isSavingMaterial",
  "isSavingMechanism",
  "isSavingMilestoneReport",
  "isSavingPartDefinition",
  "isSavingPartInstance",
  "isSavingPurchase",
  "isSavingQaReport",
  "isSavingSubsystem",
  "isSavingTask",
  "isSavingWorkLog",
  "isSavingWorkstream",
  "isWorkspaceModalOpen",
  "manufacturingDraft",
  "manufacturingModalMode",
  "materialDraft",
  "materialModalMode",
  "mechanismDraft",
  "mechanismModalMode",
  "mechanismsById",
  "mentors",
  "milestoneReportDraft",
  "milestoneReportFindings",
  "milestoneReportModalMode",
  "milestonesById",
  "notifyTaskEditCanceled",
  "partDefinitionDraft",
  "partDefinitionModalMode",
  "partDefinitionsById",
  "partInstanceDraft",
  "partInstanceModalMode",
  "partInstancesById",
  "purchaseDraft",
  "purchaseFinalCost",
  "purchaseModalMode",
  "qaReportDraft",
  "qaReportModalMode",
  "requestPhotoUpload",
  "scopedBootstrap",
  "setArtifactDraft",
  "setManufacturingDraft",
  "setMaterialDraft",
  "setMechanismDraft",
  "setMilestoneReportDraft",
  "setMilestoneReportFindings",
  "setPartDefinitionDraft",
  "setPartInstanceDraft",
  "setPurchaseDraft",
  "setPurchaseFinalCost",
  "setQaReportDraft",
  "setSubsystemDraft",
  "setSubsystemDraftRisks",
  "setTaskDraft",
  "setWorkLogDraft",
  "setWorkstreamDraft",
  "showTimelineCreateToggleInTaskModal",
  "students",
  "subsystemDraft",
  "subsystemDraftRisks",
  "subsystemModalMode",
  "taskDraft",
  "taskModalMode",
  "workLogDraft",
  "workLogModalMode",
  "workstreamDraft",
  "workstreamModalMode",
] as const;
export const shellModalTaskActionKeys = [
  "closeTaskModal",
  "closeTimelineTaskDetailsModal",
  "handleDeleteTask",
  "handleResolveTaskBlocker",
  "handleTaskSubmit",
  "openEditTaskModal",
  "openTimelineTaskDetailsModal",
  "switchTaskCreateToMilestone",
] as const;
export const shellModalReportActionKeys = [
  "closeMilestoneReportModal",
  "closeQaReportModal",
  "closeWorkLogModal",
  "handleWorkLogSubmit",
  "handleMilestoneReportSubmit",
  "handleQaReportSubmit",
] as const;
export const shellModalCatalogActionKeys = [
  "closeArtifactModal",
  "closeManufacturingModal",
  "closeMaterialModal",
  "closeMechanismModal",
  "closePartDefinitionModal",
  "closePartInstanceModal",
  "closePurchaseModal",
  "closeSubsystemModal",
  "closeWorkstreamModal",
  "handleArtifactSubmit",
  "handleDeleteArtifact",
  "handleDeleteMaterial",
  "handleDeleteMechanism",
  "handleDeletePartDefinition",
  "handleManufacturingSubmit",
  "handleMaterialSubmit",
  "handleMechanismSubmit",
  "handlePartDefinitionSubmit",
  "handlePartInstanceSubmit",
  "handlePurchaseSubmit",
  "handleSubsystemSubmit",
  "handleToggleArtifactArchived",
  "handleToggleMechanismArchived",
  "handleTogglePartDefinitionArchived",
  "handleToggleSubsystemArchived",
  "handleToggleWorkstreamArchived",
  "handleWorkstreamSubmit",
] as const;
export type AppWorkspaceShellModalLayerController = Pick<
  AppWorkspaceModel,
  (typeof shellModalLayerModelKeys)[number]
> &
  Pick<AppWorkspaceTaskActions, (typeof shellModalTaskActionKeys)[number]> &
  Pick<AppWorkspaceReportActions, (typeof shellModalReportActionKeys)[number]> &
  Pick<AppWorkspaceCatalogActions, (typeof shellModalCatalogActionKeys)[number]>;

export const shellOverlayLayerModelKeys = [
  "closeSidebarOverlay",
  "isAddSeasonPopupOpen",
  "isSavingRobotProject",
  "isSavingSeason",
  "isSidebarOverlay",
  "robotProjectModalMode",
  "robotProjectNameDraft",
  "seasonNameDraft",
  "setRobotProjectNameDraft",
  "setSeasonNameDraft",
] as const;
export const shellOverlayRosterActionKeys = [
  "closeCreateSeasonPopup",
  "closeRobotProjectPopup",
  "handleCreateSeasonSubmit",
  "handleRobotProjectSubmit",
] as const;
export type AppWorkspaceShellOverlayLayerController = Pick<
  AppWorkspaceModel,
  (typeof shellOverlayLayerModelKeys)[number]
> &
  Pick<AppWorkspaceRosterActions, (typeof shellOverlayRosterActionKeys)[number]>;
