import type { BootstrapPayload } from "@/types/bootstrap";
import { createBootstrap, isoDateOffset } from "./attentionViewModel.fixture";

export function createMentorQueueBootstrap(): BootstrapPayload {
  const bootstrap = createBootstrap();

  return {
    ...bootstrap,
    members: [
      ...bootstrap.members,
      {
        email: "mentor@example.com",
        elevated: true,
        id: "mentor-1",
        name: "Morgan Mentor",
        role: "mentor",
        seasonId: "season-1",
      },
    ],
    purchaseItems: [
      {
        approvedByMentor: false,
        estimatedCost: 325,
        id: "purchase-1",
        linkLabel: "Vendor quote",
        partDefinitionId: null,
        quantity: 2,
        requestedById: "member-1",
        status: "requested",
        subsystemId: "subsystem-1",
        title: "Order swerve bearings",
        vendor: "Bearing Co",
      },
      {
        approvedByMentor: false,
        estimatedCost: 75,
        id: "purchase-2",
        linkLabel: "Vendor quote",
        partDefinitionId: null,
        quantity: 1,
        requestedById: "member-1",
        status: "requested",
        subsystemId: "subsystem-1",
        title: "Order encoder cable",
        vendor: "Cable Co",
      },
    ],
    reports: [
      ...bootstrap.reports,
      {
        createdAt: `${isoDateOffset(-1)}T13:00:00.000Z`,
        createdByMemberId: "member-1",
        id: "report-mentor-result",
        mentorApproved: false,
        milestoneId: null,
        notes: "Iteration should be reviewed.",
        projectId: "project-1",
        reportType: "QA",
        result: "iteration-worthy",
        status: "pass",
        summary: "Iteration-worthy result",
        taskId: "task-2",
        title: "Drivetrain QA result",
        workstreamId: null,
      },
    ],
    qaReviews: [
      {
        id: "qa-review-1",
        mentorApproved: false,
        notes: "Needs mentor signoff",
        participantIds: ["member-1"],
        result: "minor-fix",
        reviewedAt: `${isoDateOffset(-1)}T12:00:00.000Z`,
        subjectId: "task-2",
        subjectTitle: "Approve drivetrain QA",
        subjectType: "task",
      },
    ],
    risks: [
      ...bootstrap.risks,
      {
        attachmentId: "project-1",
        attachmentType: "project",
        detail: "Battery mount may fail inspection",
        id: "risk-mentor-review",
        mitigationTaskId: "task-stale-mentor",
        severity: "high",
        sourceId: "report-1",
        sourceType: "qa-report",
        title: "Battery retention risk",
      },
    ],
    tasks: [
      ...bootstrap.tasks.map((task) =>
        task.id === "task-2"
          ? { ...task, mentorId: "mentor-1", title: "Approve drivetrain QA" }
          : task,
      ),
      {
        actualHours: 0,
        artifactId: null,
        artifactIds: [],
        assigneeIds: ["member-1"],
        blockers: [],

        disciplineId: "",
        documentationLinked: false,
        dueDate: isoDateOffset(7),
        estimatedHours: 1,
        id: "task-purchase",
        isBlocked: false,
        linkedManufacturingIds: [],
        linkedPurchaseIds: ["purchase-1"],
        mechanismId: null,
        mechanismIds: [],
        mentorId: "mentor-1",
        ownerId: "member-1",
        partInstanceId: null,
        partInstanceIds: [],
        planningState: "ready",
        priority: "medium",
        projectId: "project-1",
        requiresDocumentation: false,
        startDate: isoDateOffset(-2),
        status: "not-started",
        subsystemId: "subsystem-1",
        subsystemIds: ["subsystem-1"],
        summary: "Blocked on mentor purchase approval",
        targetMilestoneId: null,
        title: "Install swerve bearings",
        workstreamId: null,
        workstreamIds: [],
      },
      {
        actualHours: 0,
        artifactId: null,
        artifactIds: [],
        assigneeIds: [],
        blockers: [],

        disciplineId: "",
        documentationLinked: false,
        dueDate: isoDateOffset(4),
        estimatedHours: 1,
        id: "task-purchase-requester-only",
        isBlocked: false,
        linkedManufacturingIds: [],
        linkedPurchaseIds: ["purchase-2"],
        mechanismId: null,
        mechanismIds: [],
        mentorId: "mentor-1",
        ownerId: "mentor-1",
        partInstanceId: null,
        partInstanceIds: [],
        planningState: "ready",
        priority: "medium",
        projectId: "project-1",
        requiresDocumentation: false,
        startDate: isoDateOffset(-1),
        status: "not-started",
        subsystemId: "subsystem-1",
        subsystemIds: ["subsystem-1"],
        summary: "Requester needs mentor purchase approval.",
        targetMilestoneId: null,
        title: "Install encoder cable",
        workstreamId: null,
        workstreamIds: [],
      },
      {
        actualHours: 0,
        artifactId: null,
        artifactIds: [],
        assigneeIds: ["member-1"],
        blockers: [],

        disciplineId: "",
        documentationLinked: false,
        dueDate: isoDateOffset(5),
        estimatedHours: 3,
        id: "task-stale-mentor",
        isBlocked: false,
        linkedManufacturingIds: [],
        linkedPurchaseIds: [],
        mechanismId: null,
        mechanismIds: [],
        mentorId: "mentor-1",
        ownerId: "member-1",
        partInstanceId: null,
        partInstanceIds: [],
        planningState: "ready",
        priority: "low",
        projectId: "project-1",
        requiresDocumentation: false,
        startDate: isoDateOffset(-20),
        status: "in-progress",
        subsystemId: "subsystem-1",
        subsystemIds: ["subsystem-1"],
        summary: "Needs mentor follow-up",
        targetMilestoneId: null,
        title: "Document climb iteration",
        workstreamId: null,
        workstreamIds: [],
      },
    ],
  };
}
