import { EMPTY_BOOTSTRAP } from "@/features/workspace/shared/model/bootstrapDefaults";
import type { BootstrapPayload } from "@/types/bootstrap";

export function isoDateOffset(daysFromToday: number) {
  const target = new Date();
  target.setDate(target.getDate() + daysFromToday);
  return target.toISOString().slice(0, 10);
}

export function createBootstrap(): BootstrapPayload {
  return {
    ...EMPTY_BOOTSTRAP,
    members: [
      {
        email: "alex@example.com",
        elevated: false,
        id: "member-1",
        name: "Alex",
        role: "student",
        seasonId: "season-1",
      },
    ],
    projects: [
      {
        description: "",
        id: "project-1",
        name: "Robot",
        projectType: "robot",
        seasonId: "season-1",
        status: "active",
      },
    ],
    reports: [
      {
        createdAt: `${isoDateOffset(-1)}T10:00:00.000Z`,
        createdByMemberId: "member-1",
        id: "report-1",
        targetRefs: [{ kind: "task", id: "task-1" }],
        notes: "Needs rework",
        projectId: "project-1",
        reportType: "qa",
        result: "fail",
        status: "submitted",
        summary: "Observed failure",
        participantIds: [],
        mentorId: null,
        requestedById: null,
      },
      {
        createdAt: `${isoDateOffset(-2)}T10:00:00.000Z`,
        createdByMemberId: "member-1",
        id: "report-2",
        targetRefs: [],
        notes: "No linked task",
        projectId: "project-1",
        reportType: "qa",
        result: "fail",
        status: "submitted",
        summary: "Untracked failure",
        participantIds: [],
        mentorId: null,
        requestedById: null,
      },
    ],
    risks: [
      {
        projectId: "project-1",
        detail: "Drive burnout risk",
        id: "risk-1",
        category: "qa",
        status: "open",
        blocksWork: true,
        source: { kind: "report", id: "report-1" },
        relatedTargets: [{ kind: "task", id: "task-1" }],
        mitigationTaskId: null,
        severity: "high",
        title: "Drive overheating",
        ownerGroupId: null,
        createdAt: `${isoDateOffset(-1)}T10:00:00.000Z`,
        updatedAt: `${isoDateOffset(-1)}T10:00:00.000Z`,
        resolvedAt: null,
      },
    ],
    subsystems: [
      {
        color: "#123456",
        description: "",
        id: "subsystem-1",
        isCore: true,
        iteration: 1,
        mentorIds: [],
        name: "Drive",
        parentSubsystemId: null,
        photoUrl: "",
        projectId: "project-1",
        responsibleEngineerId: null,
      },
    ],
    tasks: [
      {
        actualHours: 0,
        assigneeIds: [],

        workTypeId: "robot-design",

        responsibleGroupId: null,
        dueDate: isoDateOffset(-1),
        estimatedHours: 2,
        id: "task-1",
        mechanismIds: [],
        mentorId: null,
        ownerId: null,
        partInstanceIds: [],
        scheduleRefs: [],
        requestedById: null,
        photoUrl: "",
        priority: "high",
        projectId: "project-1",
        checklistItems: [],
        manufacturingDetails: null,
        requiresDocumentation: false,
        startDate: isoDateOffset(-8),
        status: "in-progress",
        subsystemIds: ["subsystem-1"],
        summary: "Blocked by test stand",
        title: "Repair drive module",
        workstreamIds: [],
      },
      {
        actualHours: 0,
        assigneeIds: [],

        workTypeId: "robot-design",

        responsibleGroupId: null,
        dueDate: isoDateOffset(1),
        estimatedHours: 1,
        id: "task-2",
        mechanismIds: [],
        mentorId: null,
        ownerId: "member-1",
        partInstanceIds: [],
        scheduleRefs: [],
        requestedById: null,
        photoUrl: "",
        priority: "medium",
        projectId: "project-1",
        checklistItems: [],
        manufacturingDetails: null,
        requiresDocumentation: false,
        startDate: isoDateOffset(-6),
        status: "waiting-for-qa",
        subsystemIds: ["subsystem-1"],
        summary: "Waiting mentor QA",
        title: "Validate drivetrain tuning",
        workstreamIds: [],
      },
    ],
  };
}
