import type { BootstrapPayload } from "@/types/bootstrap";

export const EMPTY_BOOTSTRAP: BootstrapPayload = {
  seasons: [],
  projects: [],
  workstreams: [],
  members: [],
  subsystems: [],
  disciplines: [],
  mechanisms: [],
  materials: [],
  artifacts: [],
  partDefinitions: [],
  partInstances: [],
  milestones: [],
  taskDependencies: [],
  taskBlockers: [],
  reports: [],
  reportFindings: [],
  qaReports: [],
  qaRequests: [],
  testResults: [],
  qaFindings: [],
  testFindings: [],
  designIterations: [],
  risks: [],
  tasks: [],
  workLogs: [],
  meetings: [],
  attendanceRecords: [],
  purchaseItems: [],
  manufacturingItems: [],
  qaReviews: [],
  escalations: [],
  actions: [],
};
