import type { NavigationSubItem, ViewAvailabilityContext } from "./types";

export const VIEW_AVAILABILITY_CONTEXTS: readonly ViewAvailabilityContext[] = [
  "all-project",
  "robot-project",
  "non-robot-project",
  "no-project",
  "no-season",
];

export const NAVIGATION_SUB_ITEM_AVAILABILITY_MATRIX: Record<
  NavigationSubItem["id"],
  Readonly<Record<ViewAvailabilityContext, boolean>>
> = {
  "dashboard-calendar": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "dashboard-activity": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "dashboard-metrics": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "readiness-attention": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "readiness-milestones": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "readiness-subsystems": {
    "all-project": false,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": false,
    "no-season": false,
  },
  "readiness-risks": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "config-robot-model": {
    "all-project": false,
    "robot-project": true,
    "non-robot-project": false,
    "no-project": false,
    "no-season": false,
  },
  "config-cad": {
    "all-project": false,
    "robot-project": true,
    "non-robot-project": false,
    "no-project": false,
    "no-season": false,
  },
  "config-part-mappings": {
    "all-project": false,
    "robot-project": true,
    "non-robot-project": false,
    "no-project": false,
    "no-season": false,
  },
  "config-directory": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "tasks-timeline": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "tasks-board": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "tasks-manufacturing": {
    "all-project": false,
    "robot-project": true,
    "non-robot-project": false,
    "no-project": false,
    "no-season": false,
  },
  "inventory-materials": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": false,
    "no-season": false,
  },
  "inventory-parts": {
    "all-project": false,
    "robot-project": true,
    "non-robot-project": false,
    "no-project": false,
    "no-season": false,
  },
  "inventory-purchases": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": false,
    "no-season": false,
  },
  "roster-available": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "roster-workload": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "roster-attendance": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "reports-work-logs": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "reports-worklogs-kanban": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "reports-qa-forms": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
  "reports-milestone-results": {
    "all-project": true,
    "robot-project": true,
    "non-robot-project": true,
    "no-project": true,
    "no-season": false,
  },
};
