import { EMPTY_BOOTSTRAP } from "@/features/workspace/shared/model/bootstrapDefaults";
import type { BootstrapPayload } from "@/types/bootstrap";

export function createBootstrap(): BootstrapPayload {
  return {
    ...EMPTY_BOOTSTRAP,
    members: [
      {
        id: "member-1",
        name: "Alex Builder",
        email: "alex@example.com",
        role: "student",
        elevated: false,
        seasonId: "season-1",
      },
      {
        id: "member-2",
        name: "Jordan Mentor",
        email: "jordan@example.com",
        role: "mentor",
        elevated: true,
        seasonId: "season-1",
      },
    ],
    projects: [
      {
        id: "project-1",
        seasonId: "season-1",
        name: "Robot",
        projectType: "robot",
        description: "",
        status: "active",
      },
    ],
    milestones: [
      {
        id: "milestone-1",
        title: "Regional",
        type: "competition",
        status: "ready",
        startDateTime: "2026-03-10T14:00:00.000Z",
        endDateTime: null,
        isExternal: true,
        description: "Competition readiness checkpoint",
        projectIds: ["project-1"],
      },
      {
        id: "milestone-2",
        title: "Design review",
        type: "deadline",
        status: "blocked",
        startDateTime: "2026-03-12T14:00:00.000Z",
        endDateTime: null,
        isExternal: false,
        description: "Subsystem review",
        projectIds: ["project-1"],
      },
    ],
    milestoneRequirements: [
      {
        id: "milestone-2:scope:subsystem:subsystem-1",
        milestoneId: "milestone-2",
        targetType: "subsystem",
        targetId: "subsystem-1",
        conditionType: "iteration",
        conditionValue: "iteration = 1",
        required: true,
        sortOrder: 1,
        notes: "",
      },
    ],
    tasks: [
      {
        artifactIds: [],
        id: "task-1",
        projectId: "project-1",
        workstreamIds: [],
        subsystemIds: ["subsystem-1"],
        disciplineId: "discipline-1",
        mechanismIds: [],
        partInstanceIds: [],
        title: "Prep robot",
        summary: "Prepare for regional",
        status: "in-progress",
        ownerId: "member-1",
        assigneeIds: [],
        mentorId: null,
        startDate: "2026-03-01",
        dueDate: "2026-03-09",
        priority: "high",
        targetMilestoneId: "milestone-1",

        blockers: [],
        isBlocked: false,
        linkedManufacturingIds: [],
        linkedPurchaseIds: [],
        estimatedHours: 0,
        actualHours: 0,
        requiresDocumentation: false,
        documentationLinked: false,
      },
      {
        artifactIds: [],
        id: "task-2",
        projectId: "project-1",
        workstreamIds: [],
        subsystemIds: ["subsystem-1"],
        disciplineId: "discipline-1",
        mechanismIds: [],
        partInstanceIds: [],
        title: "Review drawings",
        summary: "Prepare review deck",
        status: "not-started",
        ownerId: "member-2",
        assigneeIds: [],
        mentorId: null,
        startDate: "2026-03-02",
        dueDate: "2026-03-11",
        priority: "medium",
        targetMilestoneId: null,

        blockers: [],
        isBlocked: false,
        linkedManufacturingIds: [],
        linkedPurchaseIds: [],
        estimatedHours: 0,
        actualHours: 0,
        requiresDocumentation: false,
        documentationLinked: false,
      },
    ],
    subsystems: [
      {
        id: "subsystem-1",
        projectId: "project-1",
        name: "Drive",
        description: "",
        iteration: 1,
        isCore: true,
        parentSubsystemId: null,
        responsibleEngineerId: null,
        mentorIds: [],
        risks: [],
      },
    ],
  };
}
