import type { BootstrapPayload } from "@/types/bootstrap";

const task = (id: string, status: "complete" | "not-started"): BootstrapPayload["tasks"][number] => ({
  id,
  projectId: "project-1",
  workTypeId: "robot:planning",
  responsibleGroupId: null,
  workstreamIds: [],
  title: id,
  summary: "",
  subsystemIds: ["subsystem-1"],
  mechanismIds: [],
  partInstanceIds: [],
  scheduleRefs: [],
  requestedById: null,
  ownerId: null,
  assigneeIds: [],
  mentorId: null,
  startDate: "2026-04-20",
  dueDate: "2026-04-22",
  priority: "medium",
  status,
  checklistItems: [],
  manufacturingDetails: null,
  estimatedHours: 4,
  actualHours: 0,
  requiresDocumentation: false,
});

export const bootstrap: BootstrapPayload = {
  seasons: [],
  projects: [],
  workTypes: [],
  responsibleGroups: [],
  workstreams: [],
  vendors: [],
  members: [],
  subsystems: [],
  mechanisms: [],
  materials: [],
  artifacts: [],
  partDefinitions: [],
  partInstances: [{
    id: "part-instance-1",
    partDefinitionId: "part-def-1",
    intendedSubsystemId: "subsystem-1",
    intendedMechanismId: null,
    location: { kind: "stock", location: "Parts cabinet" },
    readinessStatus: "ready",
  }],
  milestones: [{
    id: "milestone-1",
    seasonId: "season-1",
    projectIds: ["project-1"],
    title: "Milestone",
    type: "demo",
    status: "planned",
    startAt: "2026-04-20T12:00:00.000Z",
    endAt: null,
    description: "",
    readinessStatus: "ready",
  }],
  taskDependencies: [
    { id: "task-dependency-task", taskId: "task-b", kind: "task", refId: "task-a", requiredState: "complete", dependencyType: "hard", createdAt: "2026-04-20T00:00:00.000Z" },
    { id: "task-dependency-part", taskId: "task-b", kind: "part-instance", refId: "part-instance-1", requiredCondition: { kind: "derived-readiness", value: "ready" }, dependencyType: "hard", createdAt: "2026-04-20T00:00:00.000Z" },
    { id: "task-dependency-milestone", taskId: "task-b", kind: "milestone", refId: "milestone-1", requiredState: "ready", dependencyType: "soft", createdAt: "2026-04-20T00:00:00.000Z" },
  ],
  reports: [],
  qaFindings: [],
  testResults: [],
  testFindings: [],
  qaRequests: [],
  risks: [{
    id: "risk-1",
    projectId: "project-1",
    title: "Waiting on vendor shipment",
    detail: "",
    category: "supply",
    severity: "medium",
    status: "open",
    blocksWork: true,
    source: { kind: "manual" },
    relatedTargets: [{ kind: "task", id: "task-b" }],
    mitigationTaskId: null,
    ownerGroupId: null,
        ownerMemberId: null,
        mitigationDueDate: null,
    createdAt: "2026-04-20T00:00:00.000Z",
    updatedAt: "2026-04-20T00:00:00.000Z",
    resolvedAt: null,
  }],
  tasks: [task("task-a", "complete"), task("task-b", "not-started")],
  workLogs: [],
  meetings: [],
  events: [],
  attendanceRecords: [],
  purchaseItems: [],
  manufacturingProcesses: [],
  milestoneRequirements: [],
};
