import type { BootstrapPayload } from "@/types/bootstrap";

export const bootstrap = {
  seasons: [],
  projects: [],
  workstreams: [],
  members: [],
  subsystems: [],
  disciplines: [],
  mechanisms: [],
  materials: [],
  artifacts: [],
  partDefinitions: [],
  partInstances: [
    {
      id: "part-instance-1",
      subsystemId: "subsystem-1",
      mechanismId: null,
      partDefinitionId: "part-def-1",
      name: "Clamp",
      quantity: 1,
      trackIndividually: false,
      status: "ready",
    },
  ],
  milestones: [
    {
      id: "milestone-1",
      title: "Milestone",
      type: "demo",
      startDateTime: "2026-04-20T12:00:00.000Z",
      endDateTime: null,
      isExternal: false,
      description: "",
      projectIds: ["project-1"],
    },
  ],
  reports: [],
  reportFindings: [],
  qaRequests: [],
  designIterations: [],
  risks: [],
  tasks: [
    {
      artifactIds: [],
      id: "task-a",
      projectId: "project-1",
      workstreamIds: [],
      title: "Upstream task",
      summary: "",
      subsystemIds: ["subsystem-1"],
      disciplineId: "discipline-1",
      mechanismIds: [],
      partInstanceIds: [],
      targetMilestoneId: null,
      ownerId: null,
      assigneeIds: [],
      mentorId: null,
      startDate: "2026-04-20",
      dueDate: "2026-04-21",
      priority: "medium",
      status: "complete",

      blockers: [],
      linkedManufacturingIds: [],
      linkedPurchaseIds: [],
      estimatedHours: 2,
      actualHours: 0,
      requiresDocumentation: false,
      documentationLinked: false,
    },
    {
      artifactIds: [],
      id: "task-b",
      projectId: "project-1",
      workstreamIds: [],
      title: "Downstream task",
      summary: "",
      subsystemIds: ["subsystem-1"],
      disciplineId: "discipline-1",
      mechanismIds: [],
      partInstanceIds: [],
      targetMilestoneId: null,
      ownerId: null,
      assigneeIds: [],
      mentorId: null,
      startDate: "2026-04-20",
      dueDate: "2026-04-22",
      priority: "medium",
      status: "not-started",

      blockers: [],
      linkedManufacturingIds: [],
      linkedPurchaseIds: [],
      estimatedHours: 4,
      actualHours: 0,
      requiresDocumentation: false,
      documentationLinked: false,
    },
  ],
  taskDependencies: [
    {
      id: "task-dependency-task",
      workItemId: "task-b",
      sourceType: "task",
      kind: "work_item",
        refType: "task",
      refId: "task-a",
      requiredState: "complete",
      dependencyType: "hard",
      createdAt: "2026-04-20T00:00:00.000Z",
    },
    {
      id: "task-dependency-part",
      workItemId: "task-b",
      sourceType: "task",
      kind: "part_instance",
      refId: "part-instance-1",
      requiredState: "ready",
      dependencyType: "hard",
      createdAt: "2026-04-20T00:00:00.000Z",
    },
    {
      id: "task-dependency-milestone",
      workItemId: "task-b",
      sourceType: "task",
      kind: "milestone",
      refId: "milestone-1",
      requiredState: "complete",
      dependencyType: "soft",
      createdAt: "2026-04-20T00:00:00.000Z",
    },
  ],
  taskBlockers: [
    {
      id: "blocker-1",
      blockedTaskId: "task-b",
      blockerType: "other",
      blockerId: null,
      description: "Waiting on vendor shipment",
      severity: "medium",
      status: "open",
      createdByMemberId: null,
      createdAt: "2026-04-20T00:00:00.000Z",
      resolvedAt: null,
    },
  ],
  workLogs: [],
  purchaseItems: [],
  manufacturingItems: [],
} satisfies BootstrapPayload;
