export type TaskModalMode = "create" | "edit" | null;
export type PurchaseModalMode = "create" | "edit" | null;
export type ManufacturingModalMode = "create" | "edit" | null;
export type MaterialModalMode = "create" | "edit" | null;
export type PartDefinitionModalMode = "create" | "edit" | null;
export type PartInstanceModalMode = "create" | "edit" | null;
export type SubsystemModalMode = "create" | "edit" | null;
export type MechanismModalMode = "create" | "edit" | null;
export type WorkLogModalMode = "create" | null;
